sudo: true
language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"
  - "iojs"
services: rabbitmq
before_script:
  - sudo RABBITMQ_NODE_PORT=5673 RABBITMQ_SERVER_START_ARGS="-rabbit ssl_listeners [5671] -rabbit ssl_options [{cacertfile,\"test/ssl/testca/cacert.pem\"},{certfile,\"test/ssl/server/cert.pem\"},{keyfile,\"test/ssl/server/key.pem\"},{verify,verify_peer},{fail_if_no_peer_cert,false}]" RABBITMQ_NODENAME=hare rabbitmq-server -detached
  - timeout 1s openssl s_client -host localhost -port 5671
